name: Deploy Infra

on: workflow_dispatch

env:
  AWS_REGION: eu-central-1
  IAM_ROLE: arn:aws:iam::160071257600:role/lcay-iac-lab-github-actions-role

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6

      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@2ec54502e3e7b5d9591613811da6daded35caa19
        with:
          role-session-name: GitHubActionsSession
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Test
        run: terraform test -var-file=dev.tfvars

  deploy:
    needs: [test, lint]
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@2ec54502e3e7b5d9591613811da6daded35caa19
        with:
          role-session-name: GitHubActionsSession
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get aws identity
        run: |
          aws sts get-caller-identity

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Format
        run: terraform fmt --recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan & Apply
        run: terraform plan -var-file=dev.tfvars && terraform apply -var-file=dev.tfvars -auto-approve
